---
- name: "Make sure packages are installed (Debian family)"
  become: yes
  apt:
    name={{ item }}
    state=present
    update_cache=yes
    cache_valid_time=3600
  with_items: "{{ packages }}"
