---
# defaults file for ddclient
#
ddclient_daemon: 300
ddclient_syslog: yes
ddclient_mail-failure: root
ddclient_ssl: yes
ddclient_use: web
ddclient_web: loopia
ddclient_protocol: dyndns2
ddclient_server: dns.loopia.se
ddclient_login: mydomain.com
ddclient_password: MY_PASSWORD
ddclient_subdomain: mysubdomain   # {{mysubdomain}}.example.com
