- name: Debug
  ansible.builtin.debug:
    var: common_extra_disk
    verbosity: 2

- name: Add partition to volume
  become: true
  community.general.lvg:
    vg: "{{ common_extra_disk.volume_group }}"
    pvs: "{{ common_extra_disk.pvs }}"

- name: Setup data partion
  become: true
  community.general.lvol:
    vg: "{{ common_extra_disk.volume_group }}"
    lv: "{{ common_extra_disk.lv }}"
    size: "{{ common_extra_disk.size }}"
    state: present

- name: Create directory
  become: true
  ansible.builtin.file:
    path: "{{ common_extra_disk.path }}"
    state: directory
    mode: "0755"

- name: Create filesystem
  become: true
  community.general.filesystem:
    fstype: "{{ common_extra_disk.fstype }}"
    dev: "/dev/mapper/{{ common_extra_disk.volume_group }}-{{ common_extra_disk.lv }}"

- name: Mount data volume
  become: true
  ansible.posix.mount:
    path: "{{ common_extra_disk.path }}"
    src: "/dev/mapper/{{ common_extra_disk.volume_group }}-{{ common_extra_disk.lv }}"
    fstype: "{{ common_extra_disk.fstype }}"
    state: mounted
