---
# Packages are defined in vars/family/RedHat.yml
- name: Make sure packages are installed
  sudo: yes
  apt: 
    name={{ item }}
    state=present
    update_cache=yes
    cache_valid_time=3600
  with_items: packages
