---
- hosts: all
  sudo: yes
  tasks:
    - group_by: key=os_{{ ansible_distribution }}
      #changed_when: False

# CentOS specific tasks
- hosts: os_CentOS
  sudo: yes
  gather_facts: False
  vars:
    - centos_packages:
      - openssh-server
      - ntp
    - centos_services:
      - sshd
      - ntpd

  tasks:
  - name: Ensure packages are installed ( CENTOS / RHEL )
    yum: name={{ item }}  state=installed
    with_items: centos_packages

  - name: Ensure services are running ( CENTOS / RHEL )
    service: name={{ item }} state=started enabled=yes
    with_items: centos_services

# Ubuntu specific tasks
#- hosts: os_Ubuntu
  #sudo: yes
  #gather_facts: False
  #tasks:
