---
- name: "Start zigbee2mqtt docker container using version {{ zigbee2mqtt_docker_image_version }}"
  community.docker.docker_container:
    name: "{{ zigbee2mqtt_container_name }}"
    image: "koenkk/zigbee2mqtt:{{ zigbee2mqtt_docker_image_version }}"
    container_default_behavior: no_defaults
    restart_policy: always
    devices:
      - "{{ zigbee2mqtt_usb_path }}"
    published_ports:
      - 8080:8080
    volumes:
      - "{{ zigbee2mqtt_host_config_dir }}:/app/data"
    state: started
    pull: true
    env:
      TZ: Europe/Stockholm
    labels: "{{ zigbee2mqtt_docker_label | default(omit) }}"
    image_name_mismatch: recreate
