---
- name: "Start zwave_js_ui docker container using version {{ zwave_js_ui_docker_image_version }}"
  become: true
  docker_container:
    name: zwave_js_ui
    image: "zwavejs/zwave-js-ui:{{ zwave_js_ui_docker_image_version }}"
    container_default_behavior: no_defaults
    restart_policy: always
    devices:
      - "/dev/serial/by-id/usb-0658_0200-if00:/dev/zwave"
    published_ports:
      - 8091:8091
      - 3001:3000
    volumes:
      - "/opt/zwave-js-ui:/usr/src/app/store"
    state: started
    pull: true
    env:
      TZ: Europe/Stockholm
