---
- name: "Start zwavejs_ui docker container using version {{ zwavejs_ui_docker_image_version }}"
  become: true
  community.docker.docker_container:
    name: zwave_js_ui
    image: "zwavejs/zwave-js-ui:{{ zwavejs_ui_docker_image_version }}"
    container_default_behavior: no_defaults
    restart_policy: always
    devices: "{{ zwavejs_ui_devices | default([]) }}"
    image_name_mismatch: recreate
    published_ports:
      - 8091:8091
      - 3001:3001
    volumes:
      - "/opt/zwave-js-ui:/usr/src/app/store"
    state: started
    pull: true
    env:
      TZ: Europe/Stockholm
    labels: "{{ zwavejs_ui_docker_label | default(omit) }}"
