---
galaxy_info:
  author: "Jonathan Rowlands"
  description: "DDclient is a Perl client used to update dynamic DNS entries for accounts on Dynamic DNS Network Service Provider."
  license: MIT
  min_ansible_version: 1.4
  platforms:
  - name: Ubuntu
    versions:
  #  - all
  #  - lucid
  #  - maverick
  #  - natty
  #  - oneiric
  #  - precise
  #  - quantal
  #  - raring
  #  - saucy
    - trusty
  #- name: Debian
  #  versions:
  #  - all
  #  - etch
  #  - lenny
  #  - squeeze
  #  - wheezy
  #
  categories:
  - networking
  - system
dependencies: []

