---

# NOTE: Since Ansible uses Python on the backend, all boolean values are capitalized when being
# rendered (which is not valid TOML). To get around this, make sure you quote any boolean values
# (true -> "true") to ensure correct formatting (for template variables).

# InfluxDB configuration file options
influxdb_configuration_dir: /etc/influxdb
influxdb_disable_reporting: "true"
influxdb_host: localhost
influxdb_telegraf_db_name: telegraf
influxdb_root_dir: /var/lib/influxdb
influxdb_meta_dir: "{{ influxdb_root_dir }}/meta"
influxdb_retention_enabled: "true"
telegraf_influxdb_url: "http://{{ influxdb_host }}:8086"
telegraf_influxdb_db_name: "{{ influxdb_telegraf_db_name }}"