---

- name: "Deploy prometheus config file"
  become: yes
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_host_path }}/prometheus.yml"
  notify:
    - Restart prometheus

- name: "start prometheus docker container using version {{ prometheus_docker_image_version }}"
  become: yes
  docker_container:
    name: prometheus
    image: "prom/prometheus:{{ prometheus_docker_image_version }}"
    container_default_behavior: no_defaults
    restart_policy: always
    state: started
    pull: True
    user: 0
    published_ports:
      - 9090:9090
    env:
      TZ: Europe/Stockholm
    volumes:
      - "{{ prometheus_host_path }}:/etc/prometheus"
      - "{{ prometheus_host_path }}/data:/prometheus"