---
- name: "Cleanup containers"
  become: yes
  command: "docker container prune -f"

- name: "Cleanup volumes"
  become: yes
  command: "docker volume prune -f"

- name: "Cleanup images"
  become: yes
  command: "docker image prune -f -a"