# vim:ft=ansible:
---

- name: Setup home assistant user
  become: yes
  user:
   name: "{{ home_assistant_user }}"
   system: yes
   state: present

- name: "Create config dirs"
  become: yes
  file:
    state: directory
    path: "/home/{{ home_assistant_user }}/.homeassistant/{{ item }}"
    owner: "{{ home_assistant_user }}"
    group: "{{ home_assistant_user }}"
  with_items:
    - group
    - automation