---

- name: "Generate a cert for home assistant"
  become: yes
  become_user: '{{ home_assistant_user }}'
  command: "openssl req -new -x509 -sha256 -newkey rsa:4096 -nodes -subj /C=SE/CN=home.peers.se -keyout privkey.pem -days 730 -out fullchain.pem"
  args:
    chdir: '/home/{{ home_assistant_user }}/.homeassistant/'
    creates: '/home/{{ home_assistant_user }}/./homeassistant/fullchain.pem'

- name: "Copy ps4 sensor script"
  become: yes
  copy:
    src: ps4_sensor.py
    dest: "/home/{{ home_assistant_user }}/ps4_sensor.py"
    owner: "{{ home_assistant_user }}"
    group: "{{ home_assistant_user }}"
    mode: u+x

- name: "Create config dirs"
  become: yes
  file:
    state: directory
    path: "/home/{{ home_assistant_user }}/.homeassistant/{{ item }}"
    owner: "{{ home_assistant_user }}"
    group: "{{ home_assistant_user }}"
  with_items:
    - group

- name: "Deploy home assistant templates"
  become: yes
  template:
    src: "{{ item.name }}.j2"
    dest: "/home/{{ home_assistant_user }}/.homeassistant/{{ item.name }}"
    owner: "{{ home_assistant_user }}"
    group: "{{ home_assistant_user }}"
    block_start_string: "{{ item.block_start | default('{%') }}"
    block_end_string: "{{ item.block_end | default('%}') }}"
  with_items:
    - { 'name': 'automations.yaml', 'block_start': '<<', 'block_end': '>>' }
    - { 'name': 'configuration.yaml' }
    - { 'name': 'binary_sensors.yaml' }
    - { 'name': 'sensors.yaml' }
    - { 'name': 'device_trackers.yaml' }
    - { 'name': 'group/all.yaml' }
    - { 'name': 'group/home.yaml' }
    - { 'name': 'group/topfloor.yaml' }
    - { 'name': 'known_devices.yaml' }
    - { 'name': 'switches.yaml' }
    - { 'name': 'notifiers.yaml' }
    - { 'name': 'media_players.yaml' }
    - { 'name': 'scripts.yaml' }
    - { 'name': 'customizations.yaml' }
    - { 'name': 'lights.yaml' }
  notify: Restart homeassistant
  tags: hass_deploy_cfg
