---
- name: "Copy ps4 sensor script"
  become: yes
  copy:
    src: ps4_sensor.py
    dest: "/home/{{ home_assistant_user }}/ps4_sensor.py"
    owner: "{{ home_assistant_user }}"
    group: "{{ home_assistant_user }}"
    mode: u+x

- name: "Create config dirs"
  become: yes
  file:
    state: directory
    path: "/home/{{ home_assistant_user }}/.homeassistant/{{ item }}"
    owner: "{{ home_assistant_user }}"
    group: "{{ home_assistant_user }}"
  with_items:
    - group
    - automation

- name: Create home assistant DB in influxdb
  influxdb_database:
      hostname: "{{ home_assistant_influxdb_host }}"
      database_name: "home_assistant"
      state: present
  when: hass_influxdb_enabled

- name: "Deploy home assistant group templates"
  become: yes
  template:
    src: "{{ item.name }}.j2"
    dest: "/home/{{ home_assistant_user }}/.homeassistant/{{ item.name }}"
    owner: "{{ home_assistant_user }}"
    group: "{{ home_assistant_user }}"
    block_start_string: "{{ item.block_start | default('{%') }}"
    block_end_string: "{{ item.block_end | default('%}') }}"
    variable_start_string: "{{ item.variable_start | default('{{') }}"
    variable_end_string: "{{ item.variable_end | default('}}') }}"
  with_items: "{{ hass_group_templates }}"
  #- { 'name': 'group/home.yaml' }
  #  - { 'name': 'group/topfloor.yaml' }
  #  - { 'name': 'group/mainfloor.yaml' }
  #  - { 'name': 'group/basement.yaml' }
  tags: hass_deploy_cfg
  notify:
    - Check homeassistant config
    - Reload group config

- name: "Deploy home assistant automation templates"
  become: yes
  template:
    src: "{{ item.name }}.j2"
    dest: "/home/{{ home_assistant_user }}/.homeassistant/{{ item.name }}"
    owner: "{{ home_assistant_user }}"
    group: "{{ home_assistant_user }}"
    block_start_string: "{{ item.block_start | default('{%') }}"
    block_end_string: "{{ item.block_end | default('%}') }}"
    variable_start_string: "{{ item.variable_start | default('{{') }}"
    variable_end_string: "{{ item.variable_end | default('}}') }}"
  with_items:
    - { 'name': 'automation/general.yaml', 'block_start': '<<', 'block_end': '>>' }
    - { 'name': 'automation/notifies.yaml' }
    - { 'name': 'automation/security.yaml' }
    - { 'name': 'automation/basement.yaml', 'block_start': '<<', 'block_end': '>>' }
  tags: hass_deploy_cfg
  notify:
    - Check homeassistant config
    - Reload automation config

- name: "Deploy home assistant customizations templates"
  become: yes
  template:
    src: "{{ item.name }}.j2"
    dest: "/home/{{ home_assistant_user }}/.homeassistant/{{ item.name }}"
    owner: "{{ home_assistant_user }}"
    group: "{{ home_assistant_user }}"
    block_start_string: "{{ item.block_start | default('{%') }}"
    block_end_string: "{{ item.block_end | default('%}') }}"
    variable_start_string: "{{ item.variable_start | default('{{') }}"
    variable_end_string: "{{ item.variable_end | default('}}') }}"
  with_items:
    - { 'name': 'customizations.yaml' }
  tags: hass_deploy_cfg
  notify:
    - Check homeassistant config
    - Reload core config

- name: "Deploy home assistant script templates"
  become: yes
  template:
    src: "{{ item.name }}.j2"
    dest: "/home/{{ home_assistant_user }}/.homeassistant/{{ item.name }}"
    owner: "{{ home_assistant_user }}"
    group: "{{ home_assistant_user }}"
    block_start_string: "{{ item.block_start | default('{%') }}"
    block_end_string: "{{ item.block_end | default('%}') }}"
    variable_start_string: "{{ item.variable_start | default('{{') }}"
    variable_end_string: "{{ item.variable_end | default('}}') }}"
  with_items:
    - { 'name': 'scripts.yaml' }
  tags: hass_deploy_cfg
  notify:
    - Check homeassistant config
    - Reload script config

- name: "Deploy home assistant known devices templates"
  become: yes
  template:
    src: "{{ item.name }}.j2"
    dest: "/home/{{ home_assistant_user }}/.homeassistant/{{ item.name }}"
    owner: "{{ home_assistant_user }}"
    group: "{{ home_assistant_user }}"
  with_items:
    - { 'name': 'known_devices.yaml' }

- name: "Deploy home assistant templates"
  become: yes
  template:
    src: "{{ item.name }}.j2"
    dest: "/home/{{ home_assistant_user }}/.homeassistant/{{ item.name }}"
    owner: "{{ home_assistant_user }}"
    group: "{{ home_assistant_user }}"
    block_start_string: "{{ item.block_start | default('{%') }}"
    block_end_string: "{{ item.block_end | default('%}') }}"
    variable_start_string: "{{ item.variable_start | default('{{') }}"
    variable_end_string: "{{ item.variable_end | default('}}') }}"
  with_items:
    - { 'name': 'configuration.yaml' }
    - { 'name': 'binary_sensors.yaml', 'variable_start': '<<', 'variable_end': '>>' }
    - { 'name': 'sensors.yaml' }
    - { 'name': 'device_trackers.yaml' }
    - { 'name': 'switches.yaml', 'variable_start': '<<', 'variable_end': '>>' }
    - { 'name': 'notifiers.yaml' }
    - { 'name': 'media_players.yaml' }
    - { 'name': 'lights.yaml' }
    - { 'name': 'secrets.yaml' }
  tags: hass_deploy_cfg
  notify:
    - Check homeassistant config
    - Restart homeassistant
