---

- name: "Deploy home assistant templates"
  become: yes
  template:
    src: "{{ item }}.j2"
    dest: "/home/{{ home_assistant_user }}/.homeassistant/{{ item }}"
    owner: "{{ home_assistant_user }}"
    group: "{{ home_assistant_user }}"
  with_items:
    - configuration.yaml
    - automations.yaml
    - binary_sensors.yaml
  notify: Restart homeassistant
