---

- name: "Copy ps4 sensor script"
  become: yes
  copy:
    src: ps4_sensor.py
    dest: "/home/{{ home_assistant_user }}/ps4_sensor.py"
    owner: "{{ home_assistant_user }}"
    group: "{{ home_assistant_user }}"
    mode: u+x

- name: "Deploy home assistant templates"
  become: yes
  template:
    src: "{{ item }}.j2"
    dest: "/home/{{ home_assistant_user }}/.homeassistant/{{ item }}"
    owner: "{{ home_assistant_user }}"
    group: "{{ home_assistant_user }}"
  with_items:
    - configuration.yaml
    - automations.yaml
    - binary_sensors.yaml
    - sensors.yaml
    - device_trackers.yaml
    - groups.yaml
    - known_devices.yaml
    - switches.yaml
  notify: Restart homeassistant
  tags: hass_deploy_cfg
