# vim:ft=ansible:
---

- name: Setup home assistant user
  become: yes
  user:
   name: "{{ home_assistant_user }}"
   system: yes
   state: present

- name: "Create config dirs"
  become: yes
  file:
    state: directory
    path: "/home/{{ home_assistant_user }}/.homeassistant/{{ item }}"
    owner: "{{ home_assistant_user }}"
    group: "{{ home_assistant_user }}"
  with_items:
    - group
    - automation

- name: Create home assistant DB in influxdb
  influxdb_database:
      hostname: "{{ influxdb_host }}"
      database_name: "{{ hass_influxdb_database }}"
      udp_port: 4444
      state: present
  when: hass_influxdb_enabled|bool
  delegate_to: localhost
