---

- name: "Generate a cert for home assistant"
  become: yes
  become_user: '{{ home_assistant_user }}'
  command: "openssl req -new -x509 -sha256 -newkey rsa:4096 -nodes -subj /C=SE/CN=home.peers.se -keyout privkey.pem -days 730 -out fullchain.pem"
  args:
    chdir: '/home/{{ home_assistant_user }}/.homeassistant/'
    creates: '/home/{{ home_assistant_user }}/./homeassistant/fullchain.pem'

- name: "Copy ps4 sensor script"
  become: yes
  copy:
    src: ps4_sensor.py
    dest: "/home/{{ home_assistant_user }}/ps4_sensor.py"
    owner: "{{ home_assistant_user }}"
    group: "{{ home_assistant_user }}"
    mode: u+x

- name: "Deploy home assistant templates"
  become: yes
  template:
    src: "{{ item }}.j2"
    dest: "/home/{{ home_assistant_user }}/.homeassistant/{{ item }}"
    owner: "{{ home_assistant_user }}"
    group: "{{ home_assistant_user }}"
  with_items:
    - configuration.yaml
    - automations.yaml
    - binary_sensors.yaml
    - sensors.yaml
    - device_trackers.yaml
    - groups.yaml
    - known_devices.yaml
    - switches.yaml
    - notifiers.yaml
    - media_players.yaml
    - scripts.yaml
    - customizations.yaml
  notify: Restart homeassistant
  tags: hass_deploy_cfg
