---
- name: "Starting home assistant docker container with image {{ hass_image_name }}:{{ hass_docker_image_version }}"
  become: yes
  docker_container:
    name: home_assistant
    image: "{{ hass_image_name }}:{{ hass_docker_image_version }}"
    restart_policy: always
    container_default_behavior: no_defaults
    image_name_mismatch: recreate
    state: started
    pull: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "{{ home_assistant_cfg_dir }}:/config"
    devices: "{{ hass_docker_devices|default([]) }}"
    network_mode: host
    restart: "{{ hass_container_restart |default('no') }}"
    labels: "{{ homeassistant_docker_label|default(omit) }}"
  tags:
    - docker_container
    - hass-docker-container
