---

- name: "Download home assistant docker container"
  become: yes
  docker_image:
    name: "homeassistant/home-assistant:{{ hass_download_image_version| default('latest') }}"
    pull: True
  tags: docker_container
  register: hass_container_image

- name: "start home assistant docker container"
  become: yes
  docker_container:
    name: home_assistant
    image: "homeassistant/home-assistant:{{ hass_docker_image_version| default('latest') }}"
    restart_policy: always
    state: started
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "{{ home_assistant_cfg_dir }}:/config"
    devices:
      - /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A11I6JAE-if00-port0
      - /dev/serial/by-id/usb-0658_0200-if00
    network_mode: host
    restart: "{{ hass_container_restart |default('no') }}"
  tags: docker_container
