# vim:ft=ansible:
---

- name: Install required RPM packages
  become: yes
  package: 
    name: '{{ item }}'
    state: present
  with_items: "{{ home_assistant_required_packages }}"

- name: Install required python packages
  become: yes
  pip:
    executable: pip3.4
    name: '{{ item }}'
    state: latest
  with_items: '{{ home_assistant_required_python_packages }}'

- name: Setup home assistant user
  become: yes
  user:
   name: "{{ home_assistant_user }}"
   system: yes
   state: present

- name: Setup directory for home assistant
  become: yes
  file:
    path: '/home/{{ home_assistant_user }}/{{ home_assistant_dir }}'
    state: directory
    owner: '{{ home_assistant_user }}'
    group: '{{ home_assistant_user }}'

- name: Install home assistant and dependencies
  become: yes
  become_user: '{{ home_assistant_user }}'
  pip:
    name: "{{ item }}"
    state: latest
    virtualenv: '/home/{{ home_assistant_user }}/{{ home_assistant_dir }}'
    virtualenv_python: python3
  with_items:
    - homeassistant
    - websocket-client
    - pywebpush

- name: Deploy systemd config
  become: yes
  template:
    src: home-assistant.service.j2
    dest: '/etc/systemd/system/home-assistant.service'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: Enable and start home assistant
  become: yes
  service:
    name: 'home-assistant.service'
    enabled: yes
    state: started
