---
- name: "Set configuration directory path for influxdb to {{ influxdb_configuration_dir }}"
  file:
    path: "{{ influxdb_configuration_dir }}"
    state: directory

- name: Set templatized InfluxDB configuration
  template: 
    src: influxdb.conf.j2 
    dest: "{{ influxdb_configuration_dir }}/influxdb.conf"
    force: yes
    backup: yes
    owner: influxdb
    group: influxdb
    mode: 0744
  when: influxdb_template_configuration
  notify: restart influxdb
  
- name: Start the InfluxDB service
  service:
    name: influxdb
    state: started
    enabled: yes

- name: Create telegraf DB
  influxdb_database:
      hostname: "{{ influxdb_telegraf_hostname }}"
      database_name: "{{ influxdb_telegraf_db_name }}"
      state: present
  when: influxdb_telegraf_setup
