---
- name: Add Grafana {{ grafana_repo_channel }} repository [RHEL/CentOS]
  yum_repository:
    name: "grafana-{{ grafana_repo_channel }}"
    description: "Grafana Repository - {{ ansible_distribution }} $releasever"
    baseurl: "{{ grafana_repo_yum_baseurl }}"
    gpgcheck:  yes
    gpgkey: "http://grafanarel.s3.amazonaws.com/RPM-GPG-KEY-grafana"

- name: Install the grafana RPM Package
  yum:
    name: grafana
    state: present

- name: Start and enable the Grafana service
  service:
    name: grafana-server
    state: started
    enabled: yes
