---

- name: add influxdata repository
  yum_repository:
    name: influxdata
    description: "InfluxData Repository - {{ ansible_distribution }} $releasever"
    baseurl: "https://repos.influxdata.com/{{ ansible_distribution | lower }}/$releasever/$basearch/stable"
    gpgcheck:  yes
    gpgkey: "https://repos.influxdata.com/influxdb.key"
