---
- name: "Make sure influxdb RPM is not installed"
  become: true
  yum:
    name: influxdb
    state: absent

- name: "Set configuration directory path for influxdb to {{ influxdb_configuration_dir }}"
  become: yes
  file:
    path: "{{ influxdb_configuration_dir }}"
    state: directory

- name: Set templatized InfluxDB configuration
  become: yes
  template: 
    src: influxdb.conf.j2 
    dest: "{{ influxdb_configuration_dir }}/influxdb.conf"
    force: yes
    backup: yes
    mode: 0744
  notify: restart influxdb
