- name: "Start Grafana Docker Container with Version {{ grafana_docker_image_version }}"
  become: true
  community.docker.docker_container:
    name: "{{ grafana_container_name | default('grafana') }}"
    image: "grafana/grafana-oss:{{ grafana_docker_image_version }}"
    restart_policy: "{{ grafana_restart_policy | default('always') }}"
    state: started
    pull: true
    user: 0
    published_ports:
      - "{{ grafana_port | default(3000) }}:3000"
    volumes:
      - "{{ grafana_data }}/:/var/lib/grafana/"
      - "{{ grafana_datasource_dir }}/:/etc/grafana/provisioning/datasources/"
    env:
      GF_SECURITY_ADMIN_PASSWORD: "{{ grafana_admin_password | default('admin') }}"
      GF_SERVER_ROOT_URL: "{{ grafana_server_root_url }}"
    labels: "{{ grafana_docker_label | default(omit) }}"
  no_log: "{{ grafana_no_log | bool }}"
