---

- name: Import configure.yml
  ansible.builtin.import_tasks:
    file: configure.yml
  tags:
    - grafana-configure

- name: Import container.yml
  ansible.builtin.import_tasks:
    file: container.yml
  tags:
    - grafana-container
