---
- name: Create directory
  ansible.builtin.file:
    path: /opt/traefik
    state: directory
    mode: "0755"

- name: Deploy config
  ansible.builtin.template:
    src: traefik.yml.j2
    dest: /opt/traefik/dynamic.yml
    mode: "0644"

- name: "Start traefik docker container using version {{ traefik_docker_image_version }}"
  community.docker.docker_container:
    name: traefik
    image: "traefik:{{ traefik_docker_image_version }}"
    container_default_behavior: no_defaults
    command_handling: correct
    command: "{{ traefik_command_list }}"
    restart_policy: always
    state: started
    pull: true
    dns_servers: "{{ traefik_dns_servers }}"
    published_ports:
      - "80:80"
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8085:8080"
    env:
      TZ: Europe/Stockholm
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/traefik/dynamic.yml:/etc/traefik/dynamic.yml
      - /opt/traefik/acme:/etc/traefik/acme
    labels: "{{ traefik_docker_label | default(omit) }}"