---
- name: Create directory
  file:
    path: /opt/traefik
    state: directory

- name: Deploy config
  template:
    src: traefik.yml.j2
    dest: /opt/traefik/dynamic.yml

- name: "start traefik docker container using version {{ traefik_docker_image_version }}"
  docker_container:
    name: traefik
    image: "traefik:{{ traefik_docker_image_version }}"
    container_default_behavior: no_defaults
    command_handling: correct
    command:
      - --api.insecure=true
      - --providers.docker
      - --providers.file.directory=/etc/traefik
      - --providers.file.watch=true
      - --entrypoints.http
      - --entrypoints.http.address=:80
      - --entrypoints.http.forwardedheaders.insecure=true
    restart_policy: always
    state: started
    pull: True
    published_ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8085:8080"
    env:
      TZ: Europe/Stockholm
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/traefik/dynamic.yml:/etc/traefik/dynamic.yml
