---
# Packages are defined in vars/family/RedHat.yml
- name: Make sure packages are installed (RedHat family)
  become: true
  ansible.builtin.dnf:
    name: "{{ packages }}"
  when:
    - packages is defined
