---
# tasks file for dnsmasq

- name: "Run unifi-dns container"
  become: true
  docker_container:
    name: unifi-dns
    image: "wicol/unifi-dns:{{ unifi_dns_docker_version }}"
    restart_policy: always
    pull: true
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    capabilities:
    - NET_ADMIN
    env:
      UNIFI_BASEURL: '{{ unifi_base_url }}'
      UNIFI_USERNAME: '{{ unifi_username }}'
      UNIFI_PASSWORD: '{{ unifi_password }}'
      PYTHONWARNINGS: 'ignore:Unverified HTTPS request'
      LOG_LEVEL: "{{ unifi_dns_log_level }}"
    container_default_behavior: no_defaults