---

# Whether or not the playbook is run locally (changes clustering and testing logic slightly)
# This should only be set in the Vagrantfile and not modified elsewhere
is_vagrant: no

# By default, the InfluxData package repository will be used for installation. Alternatively,
# if you have a specific package/version you want to install from, you can specify a package
# URL here. Note that this does not modify any other logic, so installing older versions may
# lead to unexpected results. Use at your own risk.
influxdb_install_url:

# Whether or not to purge peer data on each run (useful for cluster testing). NOTE: This will
# cause data loss on an active cluster, so use caution
influxdb_purge_peer_data: no

# If yes, service will be started. Will not be started if set to no.
influxdb_start_service: yes

# If yes, will overwrite the packaged configuration with an Asnible/jinja2 template
influxdb_template_configuration: yes

# If supplied, will check for presence of database, and error if not found (useful for upgrade
# testing).
influxdb_verify_database_is_present: 

# Path for finding InfluxDB binaries. Added for backwards-compatibility with < 0.9.5
influxdb_binary_path: /usr/bin
