---

# the URL to hass (used by handlers)
hass_url: 'https://localhost'

# If you want to log states in influxdb
home_assistant_influxdb_host: localhost
hass_influxdb_enabled: False
hass_influxdb_database: 'home_assistant'


hass_image_variant: 'home-assistant'
hass_download_image_version: 'latest'
hass_docker_image_version: 'latest'