---

- name: Checkout repo
  git:
    repo: 'https://github.com/peerster/transfermission.git'
    dest: '{{ transfermisson_install_dir }}'

- name: Setup & install python dependencies
  pip:
    requirements: '{{ transfermisson_install_dir }}/requirements.txt'
    virtualenv: '{{ transfermisson_install_dir }}/.venv/'

- name: Setup config
  template:
    src: transfermission_config.yaml.j2
    dest: '{{ transfermisson_install_dir }}/transfermission/transfermission_config.yaml'

- name: Setup cron job
  become: true
  cron:
    cron_file: transfermission
    minute: '*/10'
    name: transfermission
    state: present
    job:  "{{ transfermisson_install_dir }}/.venv/bin/python {{ transfermisson_install_dir }}/transfermission/cli.py"
    user: root