---
- include_tasks: configure_influxdb.yml
  tags: influxdb-configure

- include_tasks: run_influxdb.yml
  become: yes
  tags: influxdb-run

- include_tasks: install_grafana.yml
  tags: grafana-install

- include_tasks: telegraf.yml
  tags: telegraf
