---

- name: Ensure telegraf RPM is not installed
  become: true
  ansible.builtin.yum:
    name: telegraf
    state: absent


- name: Create telegraf config directory
  become: true
  ansible.builtin.file:
    path: /etc/telegraf/telegraf.d
    owner: root
    group: root
    mode: '0755'
    state: directory


- name: Deploy the templates
  become: true
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ telegraf_templates }}"
  notify:
    - Restart Telegraf container


- name: Ensure Telegraf Docker container is running with version {{ telegraf_agent_version }}
  become: true
  community.docker.docker_container:
    name: telegraf
    image: "telegraf:{{ telegraf_agent_version }}"
    state: started
    restart_policy: always
    pull: true
    container_default_behavior: compatibility
    command: -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d
    published_ports:
      - 9273:9273
    volumes:
      - /:/hostfs:ro
      - /etc/telegraf:/etc/telegraf:ro
      - /proc:/hostfs/proc:ro
      - /sys:/hostfs/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/share/snmp/mibs:/usr/share/snmp/mibs
    env:
      HOST_MOUNT_PREFIX: /hostfs
      HOST_PROC: /hostfs/proc
      HOST_SYS: /hostfs/sys
