# roles/mariadb/tasks/main.yml
---

- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: mariadb

- include: install.yml
- include: config.yml
- include: root-password.yml
- include: databases.yml
- include: users.yml
