---
- name: "Download Unifi source archive"
  get_url:
    url: '{{ unifi_download_url }}'
    dest: '{{ unifi_zip_destination }}'
  delegate_to: 127.0.0.1

- name: "Install packages"
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - mongodb-server
    - java-1.8.0-openjdk

- name: "Disable mongod service"
  service:
    name: mongod
    enabled: no
    state: stopped

- name: "Setup unifi user"
  user:
    name: '{{ unifi_user }}'
    shell: '/sbin/nologin'
    createhome: no
    state: present

- name: "Download and extract unifi zip"
  unarchive:
    src: '{{ unifi_zip_destination }}' 
    dest: '{{ unifi_install_destination }}'
    owner: '{{ unifi_user }}'
    creates: '{{ unifi_install_destination }}/UniFi'

- name: "Make sure mongod symlink exists"
  file:
    src: '{{ mongod_path }}'
    dest: '{{ unifi_install_destination }}/UniFi/bin/mongod'
    state: link

- name: "Deploy unifi.service.j2 template"
  template: 
    src: unifi.service.j2
    dest: /etc/systemd/system/unifi.service
    mode: 644

- name: "Make sure data directory exist"
  file:
    dest: '{{ unifi_install_destination }}/UniFi/data'
    state: directory
    owner: '{{ unifi_user }}'

- name: "Deploy config.properties.j2 template if not present"
  template:
    src: system.properties.j2
    dest: '{{ unifi_install_destination }}/UniFi/data/system.properties'
    owner: '{{ unifi_user }}'
    force: no

- name: "Enable and start unifi service"
  service:
    name: unifi.service
    enabled: yes
    state: started
