- name: Cloud
  hosts: cloud
  remote_user: ec2-user

  tasks:
    - name: Common role
      ansible.builtin.import_role:
        name: common
      tags:
        - common

    - name: Docker role
      ansible.builtin.import_role:
        name: docker
      tags:
        - docker
      vars:
        docker_package: "docker"

    - name: Grafana role
      ansible.builtin.import_role:
        name: grafana
      tags:
        - grafana

    - name: Chrony role
      ansible.builtin.import_role:
        name: chrony
      tags:
        - chrony

    - name: Prometheus role
      ansible.builtin.import_role:
        name: prometheus
      vars:
        prometheus_retention_time: "730d"
        prometheus_template: "prometheus-cloud.yml.j2"
      tags:
        - prometheus

    - name: Traefik role
      become: true
      ansible.builtin.import_role:
        name: traefik
      tags:
        - traefik

    - name: Telegraf role
      ansible.builtin.import_role:
        name: telegraf
      tags:
        - telegraf
