---
- hosts: fileserver
  vars_files:
    - "vars/family/{{ ansible_os_family }}.yml"
  roles:
    - { role: common, tags: common }
    - { role: ddclient, tags: ddclient } 
    - { role: monitoring_server, tags: monitoring_server }
    - { role: peerster.unifi_controller, tags: unifi-controller }
    - { role: home_assistant, tags: home_assistant }
