---
- hosts: fileserver
  remote_user: peer

  vars:
    upgrade_packages: 'yes'
  vars_files:
    - "vars/family/{{ ansible_os_family }}.yml"
  roles:
    - { role: common, tags: common }
    - { role: ddclient, tags: ddclient }
    - { role: webserver, tags: webserver }
    - { role: monitoring_server, tags: monitoring_server }
    - { role: docker, tags: docker }
    - { role: mariadb, tags: mariadb, become: yes }
    - { role: home_assistant, tags: home_assistant }
    - { role: mosquitto, tags: ['mosquitto', 'docker_container'] }
    - { role: emqtt, tags: ['emqtt', 'docker_container'] }
    - { role: unifi, tags: ['unifi', 'docker_container'] }
    - { role: openvas, tags: ['openvas', 'docker_container'] }
    - { role: transmission, tags: ['transmission', 'docker_container'] }

  tasks:
    - name: "Upgrade packages"
      include_tasks: tasks/os/RedHat/upgrade_packages.yml
      tags: upgrade_packages
      when: upgrade_packages == 'yes'
