---
- hosts: fileserver
  remote_user: peer

  vars:
    upgrade_packages: 'yes'
  vars_files:
    - "vars/family/{{ ansible_os_family }}.yml"
  roles:
    - { role: common, tags: common }
    - { role: certbot, tags: certbot }
    - { role: ddclient, tags: ddclient }
    - { role: webserver, tags: webserver }
    - { role: docker, tags: docker, vars: { docker_config: True} }
    - { role: influxdb, tags: ['influxdb', 'docker_container'] }
    - { role: mariadb, tags: mariadb, become: yes }
    - { role: home_assistant, tags: home_assistant }
    - { role: grafana, tags: ['grafana','docker_container'] }
    - { role: mosquitto, tags: ['mosquitto', 'docker_container'] }
    - { role: emqtt, tags: ['emqtt', 'docker_container'] }
    - { role: unifi, tags: ['unifi', 'docker_container'] }
    - { role: transmission, tags: ['transmission', 'docker_container'] }
    - { role: sickchill, tags: ['sickchill', 'docker_container'] }
    - { role: transfermssion, tags: ['transfermission'], become: yes }
    - { role: deconz, tags: ['deconz', 'docker_container'], become: yes }
    - { role: telegraf, tags: ['telegraf', 'docker_container'], become: yes }
    - { role: unifi-nvr, tags: ['unifi_nvr', 'docker_container'], become: yes }
