---
- hosts: home
  remote_user: peer

  vars_files:
    - "vars/family/{{ ansible_os_family }}.yml"

  tasks:
    - import_role:
        name: common
      vars:
        upgrade_packages: "yes"
      tags:
        - common

    - import_role:
        name: docker
      tags:
        - docker

    - import_role:
        name: telegraf
      become: yes
      tags:
        - telegraf

- hosts: peersrv
  remote_user: peer

  roles:
    - { role: certbot, tags: certbot }
    - { role: webserver, tags: webserver }
    - { role: mariadb, tags: mariadb, become: yes }
    - { role: home_assistant, tags: home_assistant }
    - { role: grafana, tags: ["grafana", "docker_container"] }
    - { role: emqtt, tags: ["emqtt", "docker_container"] }
    - { role: unifi, tags: ["unifi", "docker_container"] }
    - { role: transmission, tags: ["transmission", "docker_container"] }
    - { role: transfermssion, tags: ["transfermission"], become: yes }
    - { role: deconz, tags: ["deconz", "docker_container"], become: yes }
    - {
        role: zwavejs2mqtt,
        tags: ["zwavejs2mqtt", "docker_container"],
        become: yes,
      }

- hosts: peernuc
  remote_user: peer

  tasks:
    - import_role:
        name: influxdb
      tags:
        - influxdb

    - import_role:
        name: mosquitto
      tags:
        - mosquitto

    - import_role:
        name: unifi-nvr
      become: yes
      vars:
        unifi_nvr_data_dir: "/mnt/data/unifi-video"
      tags:
        - unifi_nvr

    - import_role:
        name: grafana-renderer
      tags:
        - grafana-renderer

    - import_role:
        name: route53-record-updater
      tags:
        - route53-record-updater

    - import_role:
        name: unifi-dns
      tags:
        - unifi-dns
