---

- name: My Play
  hosts: home
  remote_user: peer

  tasks:
    - name: Import common role
      ansible.builtin.import_role:
        name: common
      tags:
        - common

    - name: Import docker role
      ansible.builtin.import_role:
        name: docker
      tags:
        - docker

    - name: Import pihole role
      ansible.builtin.import_role:
        name: pihole
      tags:
        - pihole

    - name: Import mosquitto role
      ansible.builtin.import_role:
        name: mosquitto
      tags:
        - mosquitto

    - name: Import unifi-nvr role
      ansible.builtin.import_role:
        name: unifi-nvr
      become: true
      tags:
        - unifi-nvr
