---
- hosts: home
  remote_user: peer

  vars:
    upgrade_packages: 'yes'
  vars_files:
    - "vars/family/{{ ansible_os_family }}.yml"
  roles:
    - { role: common, tags: common }
    - role: docker
      tags: docker
      vars:
        docker_config: False
