---
- hosts: home
  remote_user: peer

  vars_files:
    - "vars/family/{{ ansible_os_family }}.yml"

  tasks:
    - import_role:
        name: common
      vars:
        upgrade_packages: "yes"
      tags:
        - common

    - import_role:
        name: docker
      tags:
        - docker

    - import_role:
        name: telegraf
      become: yes
      tags:
        - telegraf

- hosts: peersrv
  remote_user: peer

  roles:
    - { role: home_assistant, tags: home_assistant }
    - { role: unifi, tags: ["unifi", "docker_container"] }
    - { role: zwavejs_ui, tags: ["zwavejs_ui", "docker_container"], become: true }

- hosts: peernuc
  remote_user: peer

  tasks:
    - import_role:
        name: mosquitto
      tags:
        - mosquitto

    - import_role:
        name: unifi-nvr
      become: yes
      vars:
        unifi_nvr_data_dir: "/mnt/data/unifi-video"
      tags:
        - unifi_nvr

    - import_role:
        name: route53-record-updater
      tags:
        - route53-record-updater

    - import_role:
        name: grafana
      tags:
        - grafana
      vars:

    - import_role:
        name: chrony
      tags:
        - chrony

    - import_role:
        name: prometheus
      vars:
        prometheus_retention_time: "365d"
      tags:
        - prometheus

    - import_role:
        name: zigbee2mqtt
      become: yes
      vars:
        zigbee2mqtt_usb_path: /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_d6125fe12a3bec11852ca4957a0af07f-if00-port0
        zigbee2mqtt_host_config_dir: /opt/zigbee2mqtt
        zigbee2mqtt_backup_dir: /opt/backups/zigbee2mqtt
      tags:
        - zigbee2mqtt

    - import_role:
        name: blackbox-exporter
      tags:
        - blackbox-exporter

    - import_role:
        name: pihole
      tags:
        - pihole

    - import_role:
        name: traefik
      become: yes
      tags:
        - traefik
