- name: Home
  hosts: home
  remote_user: peer

  tasks:
    - name: Common role
      ansible.builtin.import_role:
        name: common
      vars:
        upgrade_packages: "yes"
      tags:
        - common

    - name: Docker role
      ansible.builtin.import_role:
        name: docker
      tags:
        - docker

    - name: Pihole role
      ansible.builtin.import_role:
        name: pihole
      tags:
        - pihole

    - name: Mosquitto role
      ansible.builtin.import_role:
        name: mosquitto
      tags:
        - mosquitto

    - name: Unifi NVR role
      ansible.builtin.import_role:
        name: unifi-nvr
      become: true
      vars:
        unifi_nvr_data_dir: "/mnt/data/unifi-video"
      tags:
        - unifi_nvr

    - name: Route53 record updater role
      ansible.builtin.import_role:
        name: route53-record-updater
      tags:
        - route53-record-updater

    - name: Grafana role
      ansible.builtin.import_role:
        name: grafana
      tags:
        - grafana

    - name: Chrony role
      ansible.builtin.import_role:
        name: chrony
      tags:
        - chrony

    - name: Prometheus role
      ansible.builtin.import_role:
        name: prometheus
      vars:
        prometheus_retention_time: "730d"
      tags:
        - prometheus

    - name: Zigbee2mqtt role
      ansible.builtin.import_role:
        name: zigbee2mqtt
      become: true
      vars:
        zigbee2mqtt_usb_path: /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_d6125fe12a3bec11852ca4957a0af07f-if00-port0
        zigbee2mqtt_host_config_dir: /opt/zigbee2mqtt
        zigbee2mqtt_backup_dir: /opt/backups/zigbee2mqtt
      tags:
        - zigbee2mqtt

    - name: Blackbox exporter role
      ansible.builtin.import_role:
        name: blackbox-exporter
      tags:
        - blackbox-exporter

    - name: Traefik role
      ansible.builtin.import_role:
        name: traefik
      become: true
      tags:
        - traefik

    - name: Home Assistant role
      ansible.builtin.import_role:
        name: home_assistant
      tags:
        - home_assistant

    - name: ZwaveJS UI
      ansible.builtin.import_role:
        name: zwavejs_ui
      vars:
        zwavejs_ui_devices: ["/dev/serial/by-id/usb-0658_0200-if00:/dev/zwave"]
      tags:
        - zwavejs_ui
