---
- hosts: htpc
  vars_files:
    - "vars/family/{{ ansible_os_family }}.yml"
  gather_facts: false

  pre_tasks:
    - name: "Wake the HTPC"
      wakeonlan:
        mac: e0:69:95:53:23:67
      delegate_to: 127.0.0.1

    - name: Wait 300 seconds for port 22 to become open"
      wait_for:
        port: 22
        host: 192.168.7.8
        delay: 10
      connection: local

    - name: Gather facts
      setup:

  roles:
    - { role: common, tags: common }
