---
# tasks file for certbot

- name: Make sure pip packages are absent
  become: yes
  pip:
    name: 
      - requests
      - six
      - urllib3
    state: absent
  
- name: Install certbot and dependencies
  become: yes
  package:
    name:
      - certbot
      - python-requests
      - python-urllib3
    state: present


- name: Create cron job for auto renew
  become: yes
  cron:
    name: "Certbot auto renew"
    special_time: weekly
    job: "certbot renew --nginx > /tmp/certbot.log 2>&1"
